package allpage;


import java.sql.*;
import Project.*;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class CustomerCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form CustomerCheckOut
     */
    public CustomerCheckOut() {
        initComponents();
        txt_CheckInDate.setEditable(false);
        txt_CheckOutDate.setEditable(false);
        txt_CustomerMobileNumber.setEditable(false);
        txt_CustomerName.setEditable(false);
        txt_Email.setEditable(false);
        txt_NumberOfDayStay.setEditable(false);
        txt_PricePerDay.setEditable(false);
        txt_TotalAmount.setEditable(false);
    }
    int id = 0;
    String Query;
    String roomType;
    String bed;
    String roomNo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_roomNumber = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_CustomerName = new javax.swing.JTextField();
        txt_CustomerMobileNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_CheckInDate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_CheckOutDate = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_NumberOfDayStay = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_TotalAmount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_PricePerDay = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btn_CheckOut = new javax.swing.JButton();
        btn_Clear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(320, 250));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Customer Check Out.png"))); // NOI18N
        jLabel1.setText("Customer check Out");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 13, -1, -1));

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1199, 30, 39, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 78, -1, -1));

        txt_roomNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_roomNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_roomNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txt_roomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 75, 168, -1));

        btn_search.setBackground(new java.awt.Color(102, 0, 0));
        btn_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_search.setForeground(new java.awt.Color(255, 255, 255));
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 74, -1, -1));

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile Number", "Nationality", "Gender", "Email", "ID Proof", "CheckIn Date", "Room Number", "Bed", "Room Type", "Price Per Day"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 376, 1204, 209));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 141, -1, -1));

        txt_CustomerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_CustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CustomerNameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_CustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 176, 250, -1));

        txt_CustomerMobileNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_CustomerMobileNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 176, 250, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Customer Mobile Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 141, -1, -1));

        txt_CheckInDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_CheckInDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CheckInDateActionPerformed(evt);
            }
        });
        getContentPane().add(txt_CheckInDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 176, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Check In Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 141, -1, -1));

        txt_CheckOutDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_CheckOutDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 176, 250, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Check Out Date (Today)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 141, -1, -1));

        txt_NumberOfDayStay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_NumberOfDayStay, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 276, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Number of Days Stay");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 241, -1, -1));

        txt_TotalAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_TotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TotalAmountActionPerformed(evt);
            }
        });
        getContentPane().add(txt_TotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 276, 250, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Price Per Day");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 241, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total Amount to Collect From Customer");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 241, -1, -1));

        txt_PricePerDay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txt_PricePerDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 276, 250, -1));

        txt_Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 276, 250, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(979, 241, -1, -1));

        btn_CheckOut.setBackground(new java.awt.Color(102, 0, 0));
        btn_CheckOut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_CheckOut.setForeground(new java.awt.Color(255, 255, 255));
        btn_CheckOut.setText("Check Out");
        btn_CheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CheckOutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_CheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 333, -1, -1));

        btn_Clear.setBackground(new java.awt.Color(102, 0, 0));
        btn_Clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_Clear.setText("Clear");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 333, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void txt_roomNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_roomNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_roomNumberActionPerformed

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void txt_CustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CustomerNameActionPerformed

    private void txt_CheckInDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CheckInDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CheckInDateActionPerformed

    private void txt_TotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TotalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TotalAmountActionPerformed

    private void btn_CheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CheckOutActionPerformed
        // TODO add your handling code here:
        String name = txt_CustomerName.getText();
        String mobile = txt_CustomerMobileNumber.getText();
        String email = txt_Email.getText();

        String checkOut = txt_CheckOutDate.getText();
        String noOfDaysStay = txt_NumberOfDayStay.getText();
        String totalAmount = txt_TotalAmount.getText();
        roomNo = txt_roomNumber.getText();
        if (roomNo.equals("")) {
            JOptionPane.showMessageDialog(null, "Select Room");
        } else {
            Query = "Update customer set numberOfDaysStay = '" + noOfDaysStay + "',totalAmount = '" + totalAmount + "',checkOut ='" + checkOut + "' where id = '" + id + "' ";
            InsertUpdateDelete.setData(Query, "");
            Query = "update room set Status ='Not Booked' where roomNo='" + roomNo + "'";
            InsertUpdateDelete.setData(Query, "");
            String path = "E:\\Own Study\\Project\\Hotel Managment System\\Bill";
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            try {
                PdfWriter.getInstance(doc, new FileOutputStream(path + "" + id + ".pdf"));
                doc.open();
                Paragraph paragraph1 = new Paragraph("                                                     Hotel Managment System\n");
                doc.add(paragraph1);
                Paragraph paragraph2 = new Paragraph("****************************************************************************************************************");
                doc.add(paragraph2);
                Paragraph paragraph3 = new Paragraph("\tBill ID: " + id + "\nCustomer Details:\nName: " + name + "\nMobile Number: " + mobile + "\nEmail: " + email + "\n");
                doc.add(paragraph3);
                doc.add(paragraph2);
                Paragraph paragraph4 = new Paragraph("\tRoom Details:\nNumber: " + txt_roomNumber.getText() + "\nType: " + roomType + "\nbed: " + bed + "\nPrice Per Day:" + txt_PricePerDay.getText() + "");
                doc.add(paragraph4);
                doc.add(paragraph2);
                PdfPTable tb1 = new PdfPTable(4);
                tb1.addCell("Check IN Date: " + txt_CheckInDate.getText() + "");
                tb1.addCell("Check Out Date: " + txt_CheckOutDate.getText() + "");
                tb1.addCell("No of Days Stay: " + noOfDaysStay);
                tb1.addCell("Total Amount paid: " + totalAmount);
                doc.add(tb1);
                doc.add(paragraph2);
                Paragraph paragraph5 = new Paragraph("Thank you, Please Visit Again.");
                doc.add(paragraph5);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            doc.close();

            int a = JOptionPane.showConfirmDialog(null, "Do you want to print Bill", "Select", JOptionPane.YES_NO_OPTION);
            if (a == 0) {
                try {
                    if ((new File("E:\\Own Study\\Project\\Hotel Managment System\\Bill" + id + ".pdf")).exists()) {
                        Process p = Runtime
                                .getRuntime()
                                .exec("rundll32 url.FileProtocolHandler E:\\Own Study\\Project\\Hotel Managment System\\Bill" + id + ".pdf");
                    } else {
                        System.out.println("File is Not Exists");
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);

                }
            }
            setVisible(false);
            new CustomerCheckOut().setVisible(true);
        }
    }//GEN-LAST:event_btn_CheckOutActionPerformed

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_btn_ClearActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ResultSet rs = Select.getData("Select * from customer where checkout is NULL");
        DefaultTableModel model = (DefaultTableModel) tableData.getModel();

        try {
            while (rs.next()) {
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9), rs.getString(10), rs.getString(11), rs.getString(12)});
            }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        String roomNo = txt_roomNumber.getText();

        if (roomNo.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter Room Number");
        } else {
            ResultSet rs = Select.getData("select * from customer where roomNo = '" + roomNo + "' AND checkout is NULL");
            try {
                if (rs.next()) {
                    txt_roomNumber.setEditable(false);
                    id = rs.getInt(1);
                    txt_CustomerName.setText(rs.getString(2));
                    txt_CheckInDate.setText(rs.getString(9));
                    txt_CustomerMobileNumber.setText(rs.getString(3));
                    txt_PricePerDay.setText(rs.getString(13));

                    SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd");
                    Calendar cal = Calendar.getInstance();
                    txt_CheckOutDate.setText(myFormat.format(cal.getTime()));
                    String dateBeforeString = rs.getString(9);
                    java.util.Date dateBefore = myFormat.parse(dateBeforeString);
                    String dateAfterString = myFormat.format(cal.getTime());
                    java.util.Date dateAfter = myFormat.parse(dateAfterString);
                    long difference = dateAfter.getTime() - dateBefore.getTime();
                    int noOfDayStay = (int) (difference / (1000 * 60 * 60 * 24));
                    if (noOfDayStay == 0) {
                        noOfDayStay = 1;
                        txt_NumberOfDayStay.setText(String.valueOf(noOfDayStay));
                        float price = Float.parseFloat(txt_PricePerDay.getText());
                        txt_TotalAmount.setText(String.valueOf(noOfDayStay * price));
                        txt_Email.setText(rs.getString(6));
                        roomType = rs.getString(12);
                        bed = rs.getString(11);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Room number is not booked or Room Number Does not Exit");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CheckOut;
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txt_CheckInDate;
    private javax.swing.JTextField txt_CheckOutDate;
    private javax.swing.JTextField txt_CustomerMobileNumber;
    private javax.swing.JTextField txt_CustomerName;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_NumberOfDayStay;
    private javax.swing.JTextField txt_PricePerDay;
    private javax.swing.JTextField txt_TotalAmount;
    private javax.swing.JTextField txt_roomNumber;
    // End of variables declaration//GEN-END:variables
}
