package allpage;


import Project.InsertUpdateDelete;
import Project.Select;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Admin
 */
public class ForgetPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword() {
        initComponents();
    }
    String email ;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        answer_txt = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        login_btn = new javax.swing.JButton();
        signup_txt = new javax.swing.JButton();
        security_question = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        newPassword_Field = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Forget Password ?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Security Question");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Answer");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("New Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        email_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtActionPerformed(evt);
            }
        });
        getContentPane().add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 300, -1));

        search_btn.setBackground(new java.awt.Color(102, 0, 0));
        search_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        search_btn.setForeground(new java.awt.Color(255, 255, 255));
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, -1, -1));

        answer_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        answer_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_txtActionPerformed(evt);
            }
        });
        getContentPane().add(answer_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 300, -1));

        save_btn.setBackground(new java.awt.Color(102, 0, 0));
        save_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        getContentPane().add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, -1));

        login_btn.setBackground(new java.awt.Color(102, 0, 0));
        login_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login_btn.setForeground(new java.awt.Color(255, 255, 255));
        login_btn.setText("Login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, -1, -1));

        signup_txt.setBackground(new java.awt.Color(102, 0, 0));
        signup_txt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        signup_txt.setForeground(new java.awt.Color(255, 255, 255));
        signup_txt.setText("Signup");
        signup_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_txtActionPerformed(evt);
            }
        });
        getContentPane().add(signup_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, -1));

        security_question.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        security_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                security_questionActionPerformed(evt);
            }
        });
        getContentPane().add(security_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 300, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1274, 31, 40, -1));
        getContentPane().add(newPassword_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 300, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/forgot password.PNG"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void answer_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_txtActionPerformed

    private void security_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_security_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_security_questionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Exit ?", "SELECT", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtActionPerformed

    private void signup_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_txtActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new SignUp().setVisible(true);
        
    }//GEN-LAST:event_signup_txtActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_login_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        int check = 0 ;
         email = email_txt.getText();
        if(email_txt.getText().trim().isEmpty()){
            check = 1 ;
            JOptionPane.showMessageDialog(null, "Email field Required");
        }
        
        else{
            ResultSet rs = Select.getData("Select * from users where email = '"+email+"'");
            
            try {
                  if(rs.next()){
                      check = 1 ;
                      security_question.setEditable(false);
                      email_txt.setEditable(false);
                      security_question.setText(rs.getString(4));    
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
            if(check == 0){
                JOptionPane.showMessageDialog(null, "Invalid Email");
            }
            
               
        }
        
        
        
    }//GEN-LAST:event_search_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        int check = 0 ;
        String securityQuestion = security_question.getText();
        String answer = answer_txt.getText();
        String nwPass = newPassword_Field.getText();
        if(answer_txt.getText().trim().isEmpty() || nwPass.equals("")){
            check = 1 ;
            JOptionPane.showMessageDialog(null, "All field Are required");
        }
        else{
            
            ResultSet rs = Select.getData("Select * FROM users  where  email = '"+email+"' AND security_question = '"+securityQuestion+"'AND answer = '"+answer+"'");

            try {
                
                if(rs.next()){
                
                
                check = 1 ;
                InsertUpdateDelete.setData("Update users set password = '"+nwPass+"' where email = '"+email+"' ", "Password Changed");
                setVisible(false);
                new ForgetPassword().setVisible(true);
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(check == 0){
            JOptionPane.showMessageDialog(null, "Invalid answer");
        }
    }//GEN-LAST:event_save_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField newPassword_Field;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField security_question;
    private javax.swing.JButton signup_txt;
    // End of variables declaration//GEN-END:variables
}
