package allpage;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageRoom_btn = new javax.swing.JButton();
        checkIn_btn = new javax.swing.JButton();
        checkOut_btn = new javax.swing.JButton();
        billDetails_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageRoom_btn.setBackground(new java.awt.Color(255, 255, 255));
        manageRoom_btn.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        manageRoom_btn.setForeground(new java.awt.Color(102, 0, 0));
        manageRoom_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage room.png"))); // NOI18N
        manageRoom_btn.setText("manage room");
        manageRoom_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRoom_btnActionPerformed(evt);
            }
        });
        getContentPane().add(manageRoom_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 13, -1, -1));

        checkIn_btn.setBackground(new java.awt.Color(255, 255, 255));
        checkIn_btn.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        checkIn_btn.setForeground(new java.awt.Color(102, 0, 0));
        checkIn_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Customer Registration & Check IN.png"))); // NOI18N
        checkIn_btn.setText("customer check in");
        checkIn_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkIn_btnActionPerformed(evt);
            }
        });
        getContentPane().add(checkIn_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 13, -1, -1));

        checkOut_btn.setBackground(new java.awt.Color(255, 255, 255));
        checkOut_btn.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        checkOut_btn.setForeground(new java.awt.Color(102, 0, 0));
        checkOut_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Customer Check Out.png"))); // NOI18N
        checkOut_btn.setText("customer check out");
        checkOut_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOut_btnActionPerformed(evt);
            }
        });
        getContentPane().add(checkOut_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 13, -1, -1));

        billDetails_btn.setBackground(new java.awt.Color(255, 255, 255));
        billDetails_btn.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        billDetails_btn.setForeground(new java.awt.Color(102, 0, 0));
        billDetails_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Customer Details Bill.png"))); // NOI18N
        billDetails_btn.setText("Customer Details Bill");
        billDetails_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billDetails_btnActionPerformed(evt);
            }
        });
        getContentPane().add(billDetails_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(763, 13, -1, -1));

        logout_btn.setBackground(new java.awt.Color(255, 255, 255));
        logout_btn.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(102, 0, 0));
        logout_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        getContentPane().add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1052, 13, -1, -1));

        exit_btn.setBackground(new java.awt.Color(255, 255, 255));
        exit_btn.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        exit_btn.setForeground(new java.awt.Color(102, 0, 0));
        exit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        exit_btn.setText("Exit");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1215, 13, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void billDetails_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billDetails_btnActionPerformed
        // TODO add your handling code here:
        new CustomerDetailsBill().setVisible(true);
    }//GEN-LAST:event_billDetails_btnActionPerformed

    private void checkOut_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOut_btnActionPerformed
        // TODO add your handling code here:\
        new CustomerCheckOut().setVisible(true);
    }//GEN-LAST:event_checkOut_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
          int a = JOptionPane.showConfirmDialog(null, "Do you really want to close Application", "Select", JOptionPane.YES_NO_OPTION);

        if (a == 0) {
            System.exit(0);
        }    
    }//GEN-LAST:event_exit_btnActionPerformed

    private void manageRoom_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRoom_btnActionPerformed
        // TODO add your handling code here:
        new ManageRoom().setVisible(true);
    }//GEN-LAST:event_manageRoom_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
            int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout ", "Select", JOptionPane.YES_NO_OPTION);

        if (a == 0) {
            setVisible(false);
            new login().setVisible(true);
        }
    
    }//GEN-LAST:event_logout_btnActionPerformed

    private void checkIn_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkIn_btnActionPerformed
        // TODO add your handling code here:
        new CustomerCheckIn().setVisible(true);
    }//GEN-LAST:event_checkIn_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton billDetails_btn;
    private javax.swing.JButton checkIn_btn;
    private javax.swing.JButton checkOut_btn;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton manageRoom_btn;
    // End of variables declaration//GEN-END:variables
}
