package allpage;


import Project.InsertUpdateDelete;
import Project.Select;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class ManageRoom extends javax.swing.JFrame {

    /**
     * Creates new form ManageRoom
     */
    public ManageRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        close_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        roomNumber_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        roomType_combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        bed_combo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        price_txt = new javax.swing.JTextField();
        addRoom_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(320, 250));
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manage room.png"))); // NOI18N
        jLabel1.setText("Manage Room");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 13, -1, -1));

        close_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        getContentPane().add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1213, 13, 41, -1));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rooom Number", "Room Type", "Bed", "Price", "Status"
            }
        ));
        dataTable.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                dataTableComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 103, 571, 465));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Room Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 103, -1, -1));

        roomNumber_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(roomNumber_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 133, 484, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Room Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 185, -1, -1));

        roomType_combo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        roomType_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Non-AC" }));
        roomType_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomType_comboActionPerformed(evt);
            }
        });
        getContentPane().add(roomType_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 215, 484, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bed");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 267, -1, -1));

        bed_combo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bed_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple", " " }));
        getContentPane().add(bed_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 297, 484, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 359, -1, -1));

        price_txt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(price_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 389, 484, 30));

        addRoom_btn.setBackground(new java.awt.Color(102, 0, 0));
        addRoom_btn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addRoom_btn.setForeground(new java.awt.Color(255, 255, 255));
        addRoom_btn.setText("Add Room");
        addRoom_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRoom_btnActionPerformed(evt);
            }
        });
        getContentPane().add(addRoom_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 445, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/all pages background.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_close_btnActionPerformed

    private void roomType_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomType_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomType_comboActionPerformed

    private void addRoom_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRoom_btnActionPerformed
        // TODO add your handling code here:
        String roomNo = roomNumber_txt.getText();
        String roomType = (String) roomType_combo.getSelectedItem();
        String bed  = (String) bed_combo.getSelectedItem();
        String price = price_txt.getText();
        
        if(roomNumber_txt.getText().trim().isEmpty() || price_txt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"All entries Are Require");
        }
        else{
        String Query = "Insert into Room values('"+roomNo+"','"+roomType+"','"+bed+"','"+price+"','Not Booked')";
        InsertUpdateDelete.setData(Query, "Sucessfully updated");
            setVisible(false);
            new ManageRoom().setVisible(true);
        
        } 
    }//GEN-LAST:event_addRoom_btnActionPerformed

    private void dataTableComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dataTableComponentShown
        
    }//GEN-LAST:event_dataTableComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         ResultSet rs = Select.getData("select * from room");
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        
        try {
            while(rs.next()){
            model.addRow(new Object[]{rs.getString(1) , rs.getString(2) , rs.getString(3) , rs.getString(4)  ,rs.getString(5)});
        }
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addRoom_btn;
    private javax.swing.JComboBox<String> bed_combo;
    private javax.swing.JButton close_btn;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField price_txt;
    private javax.swing.JTextField roomNumber_txt;
    private javax.swing.JComboBox<String> roomType_combo;
    // End of variables declaration//GEN-END:variables
}
